#!/bin/sh
rm -rf /usr/share/enigma2/NitroAdvanceFHD
echo " " 
echo "*******************************" 
echo " "                                                         
echo "  skin successful removed....  "
echo " "    
echo "*******************************" 
echo " "  
exit 0                                               
